# This is the full, correct .gitpod.yml file
# It now uses the latest syntax and best practices.

# Define the tasks to run when the workspace starts
tasks:
  - name: Setup and Start
    init: |
      # Create VNC config and make our script executable
      mkdir -p ~/.vnc
      echo '#!/bin/bash
      xrdb $HOME/.Xresources
      startxfce4 &' > ~/.vnc/xstartup
      chmod +x ~/.vnc/xstartup
      chmod +x ./start.sh
    command: |
      # Run our startup script
      ./start.sh

# Define which ports to open
ports:
  - port: 5901
    # This just tells Gitpod to be aware of the port, but not to open a browser for it.
    onOpen: ignore

# Tell Gitpod to use our custom Dockerfile for setup
image:
  file: .gitpod.Dockerfile
